// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dater.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Sort int32

const (
	Sort_desc Sort = 0
	Sort_asc  Sort = 1
)

var Sort_name = map[int32]string{
	0: "desc",
	1: "asc",
}

var Sort_value = map[string]int32{
	"desc": 0,
	"asc":  1,
}

func (x Sort) String() string {
	return proto.EnumName(Sort_name, int32(x))
}

func (Sort) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a72ea17731102282, []int{0}
}

type Entity int32

const (
	Entity_Name  Entity = 0
	Entity_Price Entity = 1
)

var Entity_name = map[int32]string{
	0: "Name",
	1: "Price",
}

var Entity_value = map[string]int32{
	"Name":  0,
	"Price": 1,
}

func (x Entity) String() string {
	return proto.EnumName(Entity_name, int32(x))
}

func (Entity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a72ea17731102282, []int{1}
}

type FetchRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchRequest) Reset()         { *m = FetchRequest{} }
func (m *FetchRequest) String() string { return proto.CompactTextString(m) }
func (*FetchRequest) ProtoMessage()    {}
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a72ea17731102282, []int{0}
}

func (m *FetchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchRequest.Unmarshal(m, b)
}
func (m *FetchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchRequest.Marshal(b, m, deterministic)
}
func (m *FetchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchRequest.Merge(m, src)
}
func (m *FetchRequest) XXX_Size() int {
	return xxx_messageInfo_FetchRequest.Size(m)
}
func (m *FetchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchRequest proto.InternalMessageInfo

func (m *FetchRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_a72ea17731102282, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type ListSortingStruct struct {
	Sort                 Sort     `protobuf:"varint,1,opt,name=sort,proto3,enum=api.Sort" json:"sort,omitempty"`
	Entity               Entity   `protobuf:"varint,2,opt,name=entity,proto3,enum=api.Entity" json:"entity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSortingStruct) Reset()         { *m = ListSortingStruct{} }
func (m *ListSortingStruct) String() string { return proto.CompactTextString(m) }
func (*ListSortingStruct) ProtoMessage()    {}
func (*ListSortingStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_a72ea17731102282, []int{2}
}

func (m *ListSortingStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSortingStruct.Unmarshal(m, b)
}
func (m *ListSortingStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSortingStruct.Marshal(b, m, deterministic)
}
func (m *ListSortingStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSortingStruct.Merge(m, src)
}
func (m *ListSortingStruct) XXX_Size() int {
	return xxx_messageInfo_ListSortingStruct.Size(m)
}
func (m *ListSortingStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSortingStruct.DiscardUnknown(m)
}

var xxx_messageInfo_ListSortingStruct proto.InternalMessageInfo

func (m *ListSortingStruct) GetSort() Sort {
	if m != nil {
		return m.Sort
	}
	return Sort_desc
}

func (m *ListSortingStruct) GetEntity() Entity {
	if m != nil {
		return m.Entity
	}
	return Entity_Name
}

type ListPagingStruct struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPagingStruct) Reset()         { *m = ListPagingStruct{} }
func (m *ListPagingStruct) String() string { return proto.CompactTextString(m) }
func (*ListPagingStruct) ProtoMessage()    {}
func (*ListPagingStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_a72ea17731102282, []int{3}
}

func (m *ListPagingStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPagingStruct.Unmarshal(m, b)
}
func (m *ListPagingStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPagingStruct.Marshal(b, m, deterministic)
}
func (m *ListPagingStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPagingStruct.Merge(m, src)
}
func (m *ListPagingStruct) XXX_Size() int {
	return xxx_messageInfo_ListPagingStruct.Size(m)
}
func (m *ListPagingStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPagingStruct.DiscardUnknown(m)
}

var xxx_messageInfo_ListPagingStruct proto.InternalMessageInfo

func (m *ListPagingStruct) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListPagingStruct) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ListRequest struct {
	Sorting              *ListSortingStruct `protobuf:"bytes,1,opt,name=sorting,proto3" json:"sorting,omitempty"`
	Paging               *ListPagingStruct  `protobuf:"bytes,2,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a72ea17731102282, []int{4}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetSorting() *ListSortingStruct {
	if m != nil {
		return m.Sorting
	}
	return nil
}

func (m *ListRequest) GetPaging() *ListPagingStruct {
	if m != nil {
		return m.Paging
	}
	return nil
}

type ListProductObject struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Price                int64    `protobuf:"varint,2,opt,name=Price,proto3" json:"Price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProductObject) Reset()         { *m = ListProductObject{} }
func (m *ListProductObject) String() string { return proto.CompactTextString(m) }
func (*ListProductObject) ProtoMessage()    {}
func (*ListProductObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_a72ea17731102282, []int{5}
}

func (m *ListProductObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductObject.Unmarshal(m, b)
}
func (m *ListProductObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductObject.Marshal(b, m, deterministic)
}
func (m *ListProductObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductObject.Merge(m, src)
}
func (m *ListProductObject) XXX_Size() int {
	return xxx_messageInfo_ListProductObject.Size(m)
}
func (m *ListProductObject) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductObject.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductObject proto.InternalMessageInfo

func (m *ListProductObject) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListProductObject) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type ListResponse struct {
	Products             []*ListProductObject `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a72ea17731102282, []int{6}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetProducts() []*ListProductObject {
	if m != nil {
		return m.Products
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.Sort", Sort_name, Sort_value)
	proto.RegisterEnum("api.Entity", Entity_name, Entity_value)
	proto.RegisterType((*FetchRequest)(nil), "api.FetchRequest")
	proto.RegisterType((*Empty)(nil), "api.empty")
	proto.RegisterType((*ListSortingStruct)(nil), "api.ListSortingStruct")
	proto.RegisterType((*ListPagingStruct)(nil), "api.ListPagingStruct")
	proto.RegisterType((*ListRequest)(nil), "api.ListRequest")
	proto.RegisterType((*ListProductObject)(nil), "api.ListProductObject")
	proto.RegisterType((*ListResponse)(nil), "api.ListResponse")
}

func init() { proto.RegisterFile("dater.proto", fileDescriptor_a72ea17731102282) }

var fileDescriptor_a72ea17731102282 = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xdf, 0x6b, 0xe2, 0x40,
	0x10, 0xc7, 0xcd, 0xe5, 0x87, 0x3a, 0x91, 0x23, 0x0e, 0x77, 0xe2, 0x1d, 0x08, 0x92, 0x83, 0xe3,
	0xf0, 0xa8, 0x2d, 0xe9, 0x73, 0xa1, 0x48, 0xdb, 0xa7, 0xd2, 0xca, 0xfa, 0x50, 0x28, 0x7d, 0x89,
	0x71, 0xb5, 0x5b, 0x34, 0x49, 0x77, 0x37, 0x0f, 0xfe, 0xf7, 0x65, 0x67, 0x13, 0xab, 0xf4, 0x29,
	0xd9, 0xd9, 0xef, 0x7c, 0xe7, 0x33, 0xb3, 0x03, 0xe1, 0x2a, 0xd5, 0x5c, 0x4e, 0x4b, 0x59, 0xe8,
	0x02, 0xdd, 0xb4, 0x14, 0xf1, 0x18, 0x7a, 0x77, 0x5c, 0x67, 0xaf, 0x8c, 0xbf, 0x57, 0x5c, 0x69,
	0x8c, 0xc0, 0xad, 0xe4, 0x76, 0xe8, 0x8c, 0x9d, 0x7f, 0x5d, 0x66, 0x7e, 0xe3, 0x36, 0xf8, 0x7c,
	0x57, 0xea, 0x7d, 0xfc, 0x04, 0xfd, 0x7b, 0xa1, 0xf4, 0xa2, 0x90, 0x5a, 0xe4, 0x9b, 0x85, 0x96,
	0x55, 0xa6, 0x71, 0x04, 0x9e, 0x2a, 0xa4, 0xa6, 0x84, 0xef, 0x49, 0x77, 0x9a, 0x96, 0x62, 0x6a,
	0x14, 0x8c, 0xc2, 0xf8, 0x07, 0x02, 0x9e, 0x6b, 0xa1, 0xf7, 0xc3, 0x6f, 0x24, 0x08, 0x49, 0x70,
	0x4b, 0x21, 0x56, 0x5f, 0xc5, 0xd7, 0x10, 0x19, 0xe3, 0x79, 0xba, 0xf9, 0xf4, 0x1d, 0x40, 0x50,
	0xac, 0xd7, 0x8a, 0x5b, 0x67, 0x97, 0xd5, 0x27, 0xfc, 0x01, 0xfe, 0x56, 0xec, 0x84, 0x26, 0x3f,
	0x97, 0xd9, 0x43, 0x9c, 0x43, 0x68, 0x1c, 0x9a, 0x26, 0x2e, 0xa0, 0xad, 0x2c, 0x25, 0x65, 0x87,
	0xc9, 0x80, 0xca, 0x7e, 0xa1, 0x67, 0x8d, 0x0c, 0xcf, 0x20, 0x28, 0xa9, 0x3c, 0xf9, 0x86, 0xc9,
	0xcf, 0x43, 0xc2, 0x31, 0x15, 0xab, 0x45, 0xf1, 0x95, 0x1d, 0xc5, 0x5c, 0x16, 0xab, 0x2a, 0xd3,
	0x8f, 0xcb, 0x37, 0x9e, 0x69, 0x44, 0xf0, 0x1e, 0xd2, 0x1d, 0xaf, 0x67, 0x47, 0xff, 0x06, 0x77,
	0x2e, 0x45, 0xc6, 0x1b, 0x5c, 0x3a, 0xc4, 0x33, 0xe8, 0x59, 0x5c, 0x55, 0x16, 0xb9, 0xe2, 0x98,
	0x40, 0xa7, 0xb4, 0x56, 0x6a, 0xe8, 0x8c, 0xdd, 0x13, 0xe0, 0x93, 0x1a, 0xec, 0xa0, 0x9b, 0xfc,
	0x02, 0xcf, 0xf4, 0x82, 0x1d, 0xf0, 0x56, 0x5c, 0x65, 0x51, 0x0b, 0xdb, 0xe0, 0xa6, 0x2a, 0x8b,
	0x9c, 0xc9, 0x08, 0x02, 0x3b, 0x61, 0x73, 0x69, 0x30, 0xa2, 0x16, 0x76, 0x6b, 0x90, 0xc8, 0x49,
	0x5e, 0xc0, 0xbf, 0x31, 0x6b, 0x80, 0x7f, 0xc1, 0xa7, 0xb7, 0xc7, 0x3e, 0x55, 0x3b, 0xde, 0x83,
	0xdf, 0x40, 0x21, 0x7a, 0x78, 0xfc, 0x0f, 0x9e, 0x21, 0xc1, 0xe8, 0x00, 0xd5, 0xa8, 0xfa, 0x47,
	0x11, 0xdb, 0xcb, 0xac, 0xf3, 0x1c, 0x9c, 0xd3, 0x7e, 0x2d, 0x03, 0xfa, 0x5c, 0x7e, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x02, 0x23, 0x1a, 0x21, 0x75, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DaterClient is the client API for Dater service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DaterClient interface {
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*Empty, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type daterClient struct {
	cc *grpc.ClientConn
}

func NewDaterClient(cc *grpc.ClientConn) DaterClient {
	return &daterClient{cc}
}

func (c *daterClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.Dater/Fetch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daterClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/api.Dater/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaterServer is the server API for Dater service.
type DaterServer interface {
	Fetch(context.Context, *FetchRequest) (*Empty, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
}

// UnimplementedDaterServer can be embedded to have forward compatible implementations.
type UnimplementedDaterServer struct {
}

func (*UnimplementedDaterServer) Fetch(ctx context.Context, req *FetchRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}
func (*UnimplementedDaterServer) List(ctx context.Context, req *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterDaterServer(s *grpc.Server, srv DaterServer) {
	s.RegisterService(&_Dater_serviceDesc, srv)
}

func _Dater_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaterServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Dater/Fetch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaterServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dater_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaterServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Dater/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaterServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dater_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Dater",
	HandlerType: (*DaterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fetch",
			Handler:    _Dater_Fetch_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Dater_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dater.proto",
}
